# Generated by Django 4.2.30 on 2026-08-02 14:32

from django.db import migrations, models


def backfill_name_key(apps, schema_editor):
    from charts.methodology import normalize_match_key

    Artist = apps.get_model('charts', 'Artist')
    artists = list(Artist.objects.all().only('id', 'name'))
    for artist in artists:
        artist.name_key = normalize_match_key(artist.name)
    Artist.objects.bulk_update(artists, ['name_key'], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0018_chart_calculation_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='name_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Punctuation-insensitive match key, auto-derived from name. Used to catch near-duplicates (e.g. "Don\'t" vs "Dont") before a new Artist row gets created.', max_length=255),
        ),
        migrations.RunPython(backfill_name_key, migrations.RunPython.noop),
    ]
