# Generated by Django 4.2.30 on 2026-08-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0019_add_artist_name_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=20)),
                ('page', models.CharField(blank=True, default='', max_length=80)),
                ('path', models.CharField(blank=True, default='', max_length=255)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('session_id', models.CharField(blank=True, default='', max_length=64)),
                ('referrer', models.CharField(blank=True, default='', max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='siteevent_type_created_idx'), models.Index(fields=['page', '-created_at'], name='siteevent_page_created_idx')],
            },
        ),
    ]
