# Generated by Codex on 2026-08-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0020_siteevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteevent',
            name='event_type',
            field=models.CharField(max_length=32),
        ),
        migrations.AddField(
            model_name='siteevent',
            name='title',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='siteevent',
            name='search',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='siteevent',
            name='value',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='siteevent',
            name='referrer_domain',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='siteevent',
            name='utm_source',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='siteevent',
            name='utm_medium',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='siteevent',
            name='utm_campaign',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='siteevent',
            name='utm_term',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='siteevent',
            name='utm_content',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='siteevent',
            name='device_type',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='siteevent',
            name='browser',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='siteevent',
            name='os',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='siteevent',
            name='platform',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='siteevent',
            name='language',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='siteevent',
            name='timezone',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='siteevent',
            name='viewport_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteevent',
            name='viewport_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteevent',
            name='screen_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteevent',
            name='screen_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteevent',
            name='pixel_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteevent',
            name='color_depth',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteevent',
            name='connection_type',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='siteevent',
            name='effective_connection_type',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='siteevent',
            name='downlink_mbps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteevent',
            name='save_data',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteevent',
            name='page_load_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteevent',
            name='scroll_depth',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteevent',
            name='engagement_time_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteevent',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='siteevent',
            index=models.Index(fields=['session_id', '-created_at'], name='siteevent_session_created_idx'),
        ),
        migrations.AddIndex(
            model_name='siteevent',
            index=models.Index(fields=['referrer_domain', '-created_at'], name='siteevent_ref_created_idx'),
        ),
    ]
